### ISSUE TITLE
Doesn't work with Bun (`bun:test`)

### ISSUE THREAD

**Issue by talentlessguy** [DanielRamosAcosta/tepper#403]
I'm hitting this error:

```js
      at processTicksAndRejections (:61:76)
✗ Unless Middleware custom parameter test > should execute if function returns false [6.72ms]
120 |             else {
121 |                 expect(result.body).toEqual(config.expectedBody);
122 |             }
123 |         }
124 |         if (config.expectedStatus) {
125 |             expect(result.status).toEqual(config.expectedStatus);
                ^
ReferenceError: Can't find variable: expect
      at runExpectations (/home/v1rtl/Coding/tinyhttp/unless/node_modules/tepper/dist/TepperRunner.js:125:12)
      at /home/v1rtl/Coding/tinyhttp/unless/node_modules/tepper/dist/TepperRunner.js:81:8
      at processTicksAndRejections (:61:76)
✗ Unless Middleware custom parameter test > should not execute if function returns true [6.28ms]
```

My test case is this:

```ts
import { describe, it } from 'bun:test'
import { type IncomingMessage, type ServerResponse, createServer } from 'node:http'
import tepper from 'tepper'

function InitAppAndTestUnless(options: UnlessMiddlewareOptions | CustomUnless) {
  const app = createServer<typeof IncomingMessage, typeof ServerResponse>((req, res) => {
    unless({ handler: exampleMiddleware, type: 'mw' }, options)(req, res, () => {
      return
    })
    res.statusCode = 200
    res.end()
  })

  const fetch = tepper(app)

  return fetch
}

it("should execute if path string doesn't match", async () => {
  const fetch = InitAppAndTestUnless({ path: '/test' })

  await fetch.get('/').expectStatus(200).run()
})
```

I can create a reproduction snippet if needed

**Comment by DanielRamosAcosta** [comment]
tepper should be compatible with bun, I could try adding a bun test into the CI and see how it behaves

**Comment by DanielRamosAcosta** [comment]
@talentlessguy could you try again with version 1.2.0?

**Comment by talentlessguy** [comment]
I'll make a small test in a short while but it might still not be working correctly with Bun, because of this:

https://github.com/oven-sh/bun/issues/6736

**Comment by DanielRamosAcosta** [comment]
I'm closing this for now!
